import type { Metadata } from "next";
import Link from 'next/link'
import { APPLICATION_ROUTES } from "@/app/constants";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav className="flex flex-col gap-[32px] items-center justify-center min-h-screen">
          <Link href={APPLICATION_ROUTES.BOOKS}>Books</Link>
          <Link href={APPLICATION_ROUTES.GAMES}>Games</Link>
          <Link href={APPLICATION_ROUTES.MOVIES}>Movies</Link>
          <Link href={APPLICATION_ROUTES.NEWS}>News</Link>
        </nav>
      </header>
      <main className="flex flex-col gap-[32px] items-center justify-center min-h-screen">
        {children}
      </main>
      <footer className="flex flex-col gap-[32px] items-center justify-center min-h-screen">
        Created by <a href="www.linkedin.com/in/veranikashneidzer">Veranika Shneidzer</a>/
      </footer>
      </body>
    </html>
  );
}
