import type { Metadata } from "next";

import { APPLICATION_ROUTES } from "@/app/constants";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav className="flex flex-col gap-[32px] items-center justify-center min-h-screen">
          <a href={APPLICATION_ROUTES.BOOKS}>Books</a>
          <a href={APPLICATION_ROUTES.GAMES}>Games</a>
          <a href={APPLICATION_ROUTES.MOVIES}>Movies</a>
          <a href={APPLICATION_ROUTES.NEWS}>News</a>
        </nav>
      </header>
      <main className="flex flex-col gap-[32px] items-center justify-center min-h-screen">
        {children}
      </main>
      <footer className="flex flex-col gap-[32px] items-center justify-center min-h-screen">
        Created by <a href="www.linkedin.com/in/veranikashneidzer">Veranika Shneidzer</a>/
      </footer>
      </body>
    </html>
  );
}
