import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { APPLICATION_ROUTES } from "@/app/constants";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <a href={APPLICATION_ROUTES.BOOKS}>Books</a>
        <a href={APPLICATION_ROUTES.GAMES}>Games</a>
        <a href={APPLICATION_ROUTES.MOVIES}>Movies</a>
        <a href={APPLICATION_ROUTES.NEWS}>News</a>
        {children}
      </body>
    </html>
  );
}
